//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alliance
    {
        public Alliance()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int AllianceID { get; set; }
        public int Kingdom { get; set; }
        public int CityX { get; set; }
        public int CityY { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
    }
}
