//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityPayItem
    {
        public int CityPayItemID { get; set; }
        public int CityID { get; set; }
        public int PayItemID { get; set; }
        public bool Paid { get; set; }
    
        public virtual City City { get; set; }
        public virtual PayItem PayItem { get; set; }
    }
}
