//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core
    {
        public long GearID { get; set; }
        public string GearSlot { get; set; }
        public string GearName { get; set; }
        public string SetName { get; set; }
        public string BoostType { get; set; }
        public decimal RangedAttackLow { get; set; }
        public decimal RangedAttackHigh { get; set; }
        public decimal CalvaryAttackLow { get; set; }
        public decimal CalvaryAttackHigh { get; set; }
        public decimal InfantryAttackLow { get; set; }
        public decimal InfantryAttackHigh { get; set; }
        public decimal TroopAttackLow { get; set; }
        public decimal TroopAttackHigh { get; set; }
        public decimal TroopDefenseLow { get; set; }
        public decimal TroopDefenseHigh { get; set; }
        public decimal TroopHealthLow { get; set; }
        public decimal TroopHealthHigh { get; set; }
        public decimal AttackDebufLow { get; set; }
        public decimal AttackDebuffHigh { get; set; }
        public decimal HealthDebuffLow { get; set; }
        public decimal HealthDebuffHigh { get; set; }
        public decimal DefenseDebuffLow { get; set; }
        public decimal DefenseDebuffHigh { get; set; }
        public decimal MarchSpeedLow { get; set; }
        public decimal MarchSpeedHigh { get; set; }
    }
}
