//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core
    {
        public long GearID { get; set; }
        public string GearSlot { get; set; }
        public string GearName { get; set; }
        public int GearLevel { get; set; }
        public string SetName { get; set; }
        public string BoostType { get; set; }
        public decimal TroopAttackLow { get; set; }
        public decimal TroopAttackHigh { get; set; }
        public decimal TroopDefenceLow { get; set; }
        public decimal TroopDefenceHigh { get; set; }
        public decimal TroopHealthLow { get; set; }
        public decimal TroopHealthHigh { get; set; }
        public decimal StrategicTroopAttackLow { get; set; }
        public decimal StrategicTroopAttackHigh { get; set; }
        public decimal StrategicTroopDefenceLow { get; set; }
        public decimal StrategicTroopDefenceHigh { get; set; }
        public decimal StrategicTroopHealthLow { get; set; }
        public decimal StrategicTroopHealthHigh { get; set; }
        public decimal EnemyAttackDebuffLow { get; set; }
        public decimal EnemyAttackDebuffHigh { get; set; }
        public decimal EnemyStrategicAttackDebuffLow { get; set; }
        public decimal EnemyStrategicAttackDebuffHigh { get; set; }
        public decimal EnemyDefenceDebuffLow { get; set; }
        public decimal EnemyDefenceDebuffHigh { get; set; }
        public decimal EnemyStrategicDefenceDebuffLow { get; set; }
        public decimal EnemyStrategicDefenceDebuffHigh { get; set; }
        public decimal EnemyHealthDebuffLow { get; set; }
        public decimal EnemyHealthDebuffHigh { get; set; }
        public decimal EnemyStrategicHealthDebuffLow { get; set; }
        public decimal EnemyStrategicHealthDebuffHigh { get; set; }
        public decimal MarchSpeedLow { get; set; }
        public decimal MarchSpeedHigh { get; set; }
        public decimal InfantryAttackLow { get; set; }
        public decimal InfantryAttackHigh { get; set; }
        public decimal InfantryDefenceLow { get; set; }
        public decimal InfantryDefenceHigh { get; set; }
        public decimal StrategicInfantryAttackLow { get; set; }
        public decimal StrategicInfantryAttackHigh { get; set; }
        public decimal StrategicInfantryDefenceLow { get; set; }
        public decimal StrategicInfantryDefenceHigh { get; set; }
        public decimal InfantryHealthLow { get; set; }
        public decimal InfantryHealthHigh { get; set; }
        public decimal StrategicInfantryHealthLow { get; set; }
        public decimal StrategicInfantryHealthHigh { get; set; }
        public decimal EnemyInfantryAttackDebuffLow { get; set; }
        public decimal EnemyInfantryAttackDebuffHigh { get; set; }
        public decimal StratEnemyInfantryAttackDebuffLow { get; set; }
        public decimal StratEnemyInfantryAttackDebuffHigh { get; set; }
        public decimal EnemyInfantryDefenceDebuffLow { get; set; }
        public decimal EnemyInfantryDefenceDebuffHigh { get; set; }
        public decimal EnemyStrategicInfantryDefenceDebuffLow { get; set; }
        public decimal EnemyStrategicInfantryDefenceDebuffHigh { get; set; }
        public decimal EnemyStrategicInfantryHealthDebuffLow { get; set; }
        public decimal EnemyStrategicInfantryHealthDebuffHigh { get; set; }
        public decimal EnemyInfantryHealthDebuffLow { get; set; }
        public decimal EnemyInfantryHealthDebuffHigh { get; set; }
        public decimal RangedAttackLow { get; set; }
        public decimal RangedAttackHigh { get; set; }
        public decimal RangedDefenceLow { get; set; }
        public decimal RangedDefenceHigh { get; set; }
        public decimal StrategicRangedAttackLow { get; set; }
        public decimal StrategicRangedAttackHigh { get; set; }
        public decimal StrategicRangedDefenceLow { get; set; }
        public decimal StrategicRangedDefenceHigh { get; set; }
        public decimal RangedHealthLow { get; set; }
        public decimal RangedHealthHigh { get; set; }
        public decimal StrategicRangedHealthLow { get; set; }
        public decimal StrategicRangedHealthHigh { get; set; }
        public decimal EnemyRangedAttackDebuffLow { get; set; }
        public decimal EnemyRangedAttackDebuffHigh { get; set; }
        public decimal EnemyStrategicRangedAttackDebuffLow { get; set; }
        public decimal EnemyStrategicRangedAttackDebuffHigh { get; set; }
        public decimal EnemyRangedDefenceDebuffLow { get; set; }
        public decimal EnemyRangedDefenceDebuffHigh { get; set; }
        public decimal EnemyStrategicRangedDefenceDebuffLow { get; set; }
        public decimal EnemyStrategicRangedDefenceDebuffHigh { get; set; }
        public decimal EnemyRangedHealthDebuffLow { get; set; }
        public decimal EnemyRangedHealthDebuffHigh { get; set; }
        public decimal EnemyStrategicRangedHealthDebuffLow { get; set; }
        public decimal EnemyStrategicRangedHealthDebuffHigh { get; set; }
        public decimal CavalryAttackLow { get; set; }
        public decimal CavalryAttackHigh { get; set; }
        public decimal CavalryDefenceLow { get; set; }
        public decimal CavalryDefenceHigh { get; set; }
        public decimal StrategicCavalryAttackLow { get; set; }
        public decimal StrategicCavalryAttackHigh { get; set; }
        public decimal StrategicCavalryDefenceLow { get; set; }
        public decimal StrategicCavalryDefenceHigh { get; set; }
        public decimal CavalryHealthLow { get; set; }
        public decimal CavalryHealthHigh { get; set; }
        public decimal StrategicCavalryHealthLow { get; set; }
        public decimal StrategicCavalryHealthHigh { get; set; }
        public decimal EnemyCavalryAttackDebuffLow { get; set; }
        public decimal EnemyCavalryAttackDebuffHigh { get; set; }
        public decimal StrategicEnemyCavalryAttackDebuffLow { get; set; }
        public decimal StrategicEnemyCavalryAttackDebuffHigh { get; set; }
        public decimal EnemyCavalryDefenceDebuffLow { get; set; }
        public decimal EnemyCavalryDefenceDebuffHigh { get; set; }
        public decimal StrategicEnemyCavalryDefenceDebuffLow { get; set; }
        public decimal StrategicEnemyCavalryDefenceDebuffHigh { get; set; }
        public decimal EnemyCavalryHealthDebuffLow { get; set; }
        public decimal EnemyCavalryHealthDebuffHigh { get; set; }
        public decimal StrategicEnemyCavalryHealthDebuffLow { get; set; }
        public decimal StrategicEnemyCavalryHealthDebuffHigh { get; set; }
        public decimal SiegeAttackLow { get; set; }
        public decimal SiegeAttackHigh { get; set; }
        public decimal SiegeDefenceLow { get; set; }
        public decimal SiegeDefenceHigh { get; set; }
        public decimal TrapDefenseLow { get; set; }
        public decimal TrapDefenseHigh { get; set; }
        public decimal StrategicTrapDefenseLow { get; set; }
        public decimal StrategicTrapDefenseHigh { get; set; }
        public decimal TroopTrainingSpeedLow { get; set; }
        public decimal TroopTrainingSpeedHigh { get; set; }
        public decimal TrapDefenceLow { get; set; }
        public decimal TrapDefenceHigh { get; set; }
        public decimal StrategicTrapDefenceLow { get; set; }
        public decimal StrategicTrapDefenceHigh { get; set; }
        public decimal TroopTrainingSpeedLow1 { get; set; }
        public decimal TroopTrainingSpeedHigh1 { get; set; }
        public decimal EnemySiegeAttackDebuffLow { get; set; }
        public decimal EnemySiegeAttackDebuffHigh { get; set; }
        public decimal StrategicTrapAttackLow { get; set; }
        public decimal StrategicTrapAttackHigh { get; set; }
        public decimal TrapAttackLow { get; set; }
        public decimal TrapAttackHigh { get; set; }
        public decimal HeroCriticalLow { get; set; }
        public decimal HeroCriticalHigh { get; set; }
        public decimal MonsterDebuffLow { get; set; }
        public decimal MonsterDebuffHigh { get; set; }
    }
}
