//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public string MachineID { get; set; }
        public int Severity { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string Message { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
