//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Cities = new HashSet<City>();
            this.Logs = new HashSet<Log>();
        }
    
        public int LoginID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public System.DateTime LastRun { get; set; }
        public string InProcess { get; set; }
        public string PIN { get; set; }
        public int LoginDelayMin { get; set; }
        public int LoginAttempts { get; set; }
        public bool Paid { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
