//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.SubscriptionItems = new HashSet<SubscriptionItem>();
        }
    
        public int SubscriptionID { get; set; }
        public string Email { get; set; }
        public bool Paid { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<System.DateTime> LastPaid { get; set; }
        public string PaypalEmail { get; set; }
        public string PaypalTxnID { get; set; }
        public string PaypalPayerID { get; set; }
        public string PaypalSubscriberID { get; set; }
    
        public virtual ICollection<SubscriptionItem> SubscriptionItems { get; set; }
    }
}
