//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionItem
    {
        public int SubscriptionID { get; set; }
        public int CityPayItemID { get; set; }
        public Nullable<int> fake { get; set; }
    
        public virtual CityPayItem CityPayItem { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
