//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GowWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPayItem
    {
        public string Email { get; set; }
        public int PayItemID { get; set; }
        public bool Paid { get; set; }
        public int UserPayItemID { get; set; }
    
        public virtual PayItem PayItem { get; set; }
    }
}
